<?php

namespace App\Models;


class Comment extends Base
{
    public function save(array $options = [])
    {
        $post = parent::save($options);

        // 写入ela
        $jobData = [
            'type' => 'comment',
            'action' => 'save',
            'id' => $this->id,
        ];
        // 分发任务
        dispatch(new \App\Jobs\ElasticsearchTodoJob($jobData));

        return $post; // TODO: Change the autogenerated stub
    }

    public function delete()
    {
        $post = parent::delete();

        // 写入ela
        $jobData = [
            'type' => 'comment',
            'action' => 'delete',
            'id' => $this->id,
        ];
        dispatch(new \App\Jobs\ElasticsearchTodoJob($jobData));

        return $post; // TODO: Change the autogenerated stub
    }

    // 评论所属文章
    public function post()
    {
        return $this->belongsTo('App\Models\Post', 'post_id', 'id');
    }

    // 评论所属的用户
    public function user()
    {
        return $this->belongsTo('App\Models\User', 'user_id', 'id');
    }
}
